// Generated by CoffeeScript 1.6.2
(function() {
  $(window).load(function() {
    var scrollHintFooter, scrollHintHeader;

    $("body").append("<div class=\"scrollhint\">\n  <div class=\"header\"></div>\n  <div class=\"footer\"></div>\n</div>");
    scrollHintHeader = $(".scrollhint .header");
    scrollHintFooter = $(".scrollhint .footer");
    return $(window).scroll(function() {
      var documentHeight, pagePosition, position, scrollTop, shaderHeight, windowHeight;

      shaderHeight = 20;
      documentHeight = $(document).height();
      windowHeight = $(window).height();
      scrollTop = $(window).scrollTop();
      pagePosition = documentHeight - windowHeight - shaderHeight;
      position = pagePosition - scrollTop;
      if (position > 0) {
        position = 0;
      }
      scrollHintFooter.css("bottom", position);
      position = (-scrollTop + shaderHeight) * -1;
      if (position > 0) {
        position = 0;
      }
      return scrollHintHeader.css("top", position);
    });
  });

}).call(this);
